Repository levxyca/hacktoberfest, pull requests merged in 2021-10, with the labels that each got.

#7 :memo: Arrumado redirecionamento para o artigo
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#8 :memo: update badges
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#9 :memo: remove badge hacktoberfest
  README.md
Labels: bug, documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#10 :lipstick: Modificado o título principal do site
  css/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#5 changed section's color
  css/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted
